name: tv_app
description: ZigHotels Tv App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../packages/common
  translations:
    path: ../packages/translations
  zig_assets:
    path: ../packages/zig_assets
  network:
    path: ../packages/network

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  dimensions_theme: ^0.0.3
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  fluttertoast: ^8.2.2
  flutter_staggered_grid_view: ^0.6.2
  http: ^1.0.0
  geolocator: ^9.0.2
  flutter_downloader: ^1.10.4
  flutter_install_app: ^1.3.0
  flutter_install_apk_silently: ^0.2.0
  device_apps: ^2.2.0
  android_intent: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Waterfall
      fonts:
        - asset: packages/common/src/assets/fonts/Waterfall/Waterfall-Regular.ttf
          weight: 400
    - family: Ubuntu
      fonts:
        - asset: packages/common/src/assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: packages/common/src/assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/common/src/assets/fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: packages/common/src/assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: packages/common/src/assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/common/src/assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: packages/common/src/assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/common/src/assets/fonts/Ubuntu-Regular.ttf
          weight: 400
