name: tv_app
description: ZigHotels Tv App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../packages/common
  translations:
    path: ../packages/translations
  zig_assets:
    path: ../packages/zig_assets

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: ../packages/common/lib/src/assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: ../packages/common/lib/src/assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: ../packages/common/lib/src/assets/fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: ../packages/common/lib/src/assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: ../packages/common/lib/src/assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: ../packages/common/lib/src/assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: ../packages/common/lib/src/assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: ../packages/common/lib/src/assets/fonts/Ubuntu-Regular.ttf
          weight: 400
